// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final String _apiKeyWeb = dotenv.env['FIREBASE_API_KEY_WEB'] ?? '';
  static final String _apiKeyAndroid = dotenv.env['FIREBASE_API_KEY_ANDROID'] ?? '';
  static final String _apiKeyIos = dotenv.env['FIREBASE_API_KEY_IOS'] ?? '';
  static final String _apiKeyMacos = dotenv.env['FIREBASE_API_KEY_MACOS'] ?? '';
  static final String _apiKeyWindows = dotenv.env['FIREBASE_API_KEY_WINDOWS'] ?? '';


  static final FirebaseOptions web = FirebaseOptions(
    apiKey: _apiKeyWeb,
    appId: '1:755701620617:web:169bfaad009bc254c38b58',
    messagingSenderId: '755701620617',
    projectId: 'fir-b8753',
    authDomain: 'fir-b8753.firebaseapp.com',
    storageBucket: 'fir-b8753.firebasestorage.app',
    measurementId: 'G-FD2EFVMYXB',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: _apiKeyAndroid,
    appId: '1:755701620617:android:f4c6aa3c8164be95c38b58',
    messagingSenderId: '755701620617',
    projectId: 'fir-b8753',
    storageBucket: 'fir-b8753.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: _apiKeyIos,
    appId: '1:755701620617:ios:52b4f5bda3039d28c38b58',
    messagingSenderId: '755701620617',
    projectId: 'fir-b8753',
    storageBucket: 'fir-b8753.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotification',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: _apiKeyMacos,
    appId: '1:755701620617:ios:52b4f5bda3039d28c38b58',
    messagingSenderId: '755701620617',
    projectId: 'fir-b8753',
    storageBucket: 'fir-b8753.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotification',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: _apiKeyWindows,
    appId: '1:755701620617:web:7158e8f9b01d556cc38b58',
    messagingSenderId: '755701620617',
    projectId: 'fir-b8753',
    authDomain: 'fir-b8753.firebaseapp.com',
    storageBucket: 'fir-b8753.firebasestorage.app',
    measurementId: 'G-E0P0TRMQD9',
  );
}
