// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVmAjT2WBKxV7XkQpBlRQTBnQ2OfKaNfA',
    appId: '1:755701620617:web:169bfaad009bc254c38b58',
    messagingSenderId: '755701620617',
    projectId: 'fir-b8753',
    authDomain: 'fir-b8753.firebaseapp.com',
    storageBucket: 'fir-b8753.firebasestorage.app',
    measurementId: 'G-FD2EFVMYXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_W5JYnHVB93Lur8Aoq8ZFK5kTZ6ktF_0',
    appId: '1:755701620617:android:90cc01c094751dd8c38b58',
    messagingSenderId: '755701620617',
    projectId: 'fir-b8753',
    storageBucket: 'fir-b8753.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRpMrigZT3gbW0dGzf_KzT-LDhlmtUjvA',
    appId: '1:755701620617:ios:8970d0c2401742a6c38b58',
    messagingSenderId: '755701620617',
    projectId: 'fir-b8753',
    storageBucket: 'fir-b8753.firebasestorage.app',
    iosBundleId: 'com.example.remoteNotification',
  );
}
